# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logging.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'logging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlogging.proto\x12\x07logging\"$\n\x03Log\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x0e\x41\x64\x64LogResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x10\n\x0eGetLogsRequest\"!\n\nLogsString\x12\x13\n\x0blogs_string\x18\x01 \x01(\t\"\"\n\x04Logs\x12\x1a\n\x04logs\x18\x01 \x03(\x0b\x32\x0c.logging.Log2z\n\x0eLoggingService\x12/\n\x06\x41\x64\x64Log\x12\x0c.logging.Log\x1a\x17.logging.AddLogResponse\x12\x37\n\x07GetLogs\x12\x17.logging.GetLogsRequest\x1a\x13.logging.LogsStringb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOG']._serialized_start=26
  _globals['_LOG']._serialized_end=62
  _globals['_ADDLOGRESPONSE']._serialized_start=64
  _globals['_ADDLOGRESPONSE']._serialized_end=97
  _globals['_GETLOGSREQUEST']._serialized_start=99
  _globals['_GETLOGSREQUEST']._serialized_end=115
  _globals['_LOGSSTRING']._serialized_start=117
  _globals['_LOGSSTRING']._serialized_end=150
  _globals['_LOGS']._serialized_start=152
  _globals['_LOGS']._serialized_end=186
  _globals['_LOGGINGSERVICE']._serialized_start=188
  _globals['_LOGGINGSERVICE']._serialized_end=310
# @@protoc_insertion_point(module_scope)
